server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27019/librasys_auth}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

api:
  key: auth-service-key-2026

jwt:
  secret: LibraSys2026SuperSecretKeyForJWTSigningMustBeAtLeast256Bits!!
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
