server:
  port: 8083

spring:
  application:
    name: loan-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27021/librasys_loans}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: localhost
    status-page-url: http://localhost:8083/swagger-ui/index.html
    home-page-url: http://localhost:8083/swagger-ui/index.html

api:
  key: loan-service-key-2026

services:
  book-service:
    url: ${SERVICES_BOOK_SERVICE_URL:http://localhost:8082}
    api-key: ${SERVICES_BOOK_SERVICE_API_KEY:book-service-key-2026}
  notification-service:
    url: ${SERVICES_NOTIFICATION_SERVICE_URL:http://localhost:8085}
    api-key: ${SERVICES_NOTIFICATION_SERVICE_API_KEY:notification-service-key-2026}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
